fileName=support-reporting-level1.ipynb
nbupdate:
	jupyter nbconvert --execute --to notebook --inplace ${fileName}
	jupyter nbconvert --to python ${fileName}
	jupyter nbconvert --to html ${fileName}
	jupyter nbconvert --to pdf ${fileName}
